language: python
sudo: false
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -r requirements_dev.txt
    - npm install -g grunt-cli bower
    - npm install
script:
    - npm run build
    - python manage.py migrate --fake-initial
    - python manage.py compile_frontend
    - python manage.py test

# Simple smoke tests
after_deploy:
  - curl --silent --fail --head https://fec-dev-eregs.18f.gov || travis_terminate $?
  - curl --silent --fail --get https://fec-dev-eregs.18f.gov/api/regulation/2 > /dev/null || travis_terminate $?

# This does not handle zero-downtime deployments
deploy:
  edge: true
  provider: cloudfoundry
  username: fec_deployer
  password:
    secure: "b80cT6KZIxfwt5KkhNQKsKSCX6v2s97H+JR6cJ/sZtJ9KFB+P2HJ2ievVYAgtZcfkGVKLpcryxio1WyliXVpJLtQK9srfL///M1fZans2GvYdLcJ/Cc+KDXDUxKMzCdX4tt4mbHutt1Kfeyz0cCD3xrjny+g6r+7/SnerHs+zYZKufSk2FN6S0ylsxgiHxyd7I0YkcO540vLONISVZELjc28b5pfUlheKNxNwfesBhRnlsE3ArWFlqrexVvOU8Gc1lRBQm6Ks3bbR46MNzaoJIIZd/xSIgeoY96ZFROdEQUYRH5O08deBKS9SYvlVWBTmhwEDylT10DIyxaotSATnDVuvXvH86vm2TNKoDFC+dNNj9hM64AaKMN2a5IA8shRip8LQ1IoO7o7VMeS38z6EGphKb5W/HaeyOJRZnAPxPFmjOoBukpK+Rav9gphz+dpwJrXnHrntIi7yGRf9i3qOFfGh82qXAw81cJCZ7GKeN31qo8IblBxux9BfERZPR37fJGiaP4JW3hVS//MyhBWIUL80YZD6TJSdxxUEP+vAOe05EDgkpehpZxMCDVR4REUFNb4eB8u1THGujxkatglkz32cXGbCRCIfLG8CzBGZDUvMcKyla11ulWsT8HoO3wrtc6BzMDRrQappmtpi0wrlfx50avqDO+zDp5wB0wi1VU="
  api: https://api.cloud.gov
  organization: fec
  space: dev
  manifest: manifest.dev.yml
  skip_cleanup: true
  on:
    branch: travis
